// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx5h3QCv-RXVJ76lj7zHJlp2FRH955eC8',
    appId: '1:182391574782:web:fddf3de99719c398e655af',
    messagingSenderId: '182391574782',
    projectId: 'english-learning-app-1a343',
    authDomain: 'english-learning-app-1a343.firebaseapp.com',
    storageBucket: 'english-learning-app-1a343.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wuWLmhcrwQR-37hcVmL0F7o1ND6dLsA',
    appId: '1:182391574782:android:b9beee8b4a5c9109e655af',
    messagingSenderId: '182391574782',
    projectId: 'english-learning-app-1a343',
    storageBucket: 'english-learning-app-1a343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACPhWYUwvXr4PPMrYgiKA-E_JbdcwXNPk',
    appId: '1:182391574782:ios:5a3a2df1bd9861fce655af',
    messagingSenderId: '182391574782',
    projectId: 'english-learning-app-1a343',
    storageBucket: 'english-learning-app-1a343.firebasestorage.app',
    iosBundleId: 'com.example.englishlearningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACPhWYUwvXr4PPMrYgiKA-E_JbdcwXNPk',
    appId: '1:182391574782:ios:5a3a2df1bd9861fce655af',
    messagingSenderId: '182391574782',
    projectId: 'english-learning-app-1a343',
    storageBucket: 'english-learning-app-1a343.firebasestorage.app',
    iosBundleId: 'com.example.englishlearningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx5h3QCv-RXVJ76lj7zHJlp2FRH955eC8',
    appId: '1:182391574782:web:f936b53cbddaebb7e655af',
    messagingSenderId: '182391574782',
    projectId: 'english-learning-app-1a343',
    authDomain: 'english-learning-app-1a343.firebaseapp.com',
    storageBucket: 'english-learning-app-1a343.firebasestorage.app',
  );
}
